apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "agent.fullname" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "agent.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: ServiceAccount
  name: {{ template "agent.fullname" . }}
  namespace: {{ .Release.Namespace }}
  

--- 
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "agent.fullname" . }}
rules:
- apiGroups:
  - ""
  resources:
  {{- range .Values.resource_types }}
    - {{.}}
  {{- end }}

  verbs:
  - get