apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ template "agent.fullname" . }}
spec:
  schedule: {{ .Values.schedule | quote }}
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      activeDeadlineSeconds: 600
      backoffLimit: 3
      template:
        spec:
          serviceAccountName: {{ template "agent.fullname" . }}
          restartPolicy: Never
          containers:
          - name: reporting-agent
            image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
            env:
            - name: ELASTICSEARCH_INDEX_URL
              value: {{ .Values.elasticsearch_url }}/{{ .Values.index }}
            - name: RESOURCE_TYPES
              value: {{ .Values.resource_types | join "," }}
            - name: CLUSTER
              value: {{ .Values.cluster }}
