version: 2
jobs:
  build:
    machine: true
    steps:
    - checkout

    - run:
        name: install helm
        command: .circleci/install.sh
    - run:
        name: helm lint
        command: helm lint ./helm/reporting-agent-chart
    - run:
        name: docker login
        command: docker login -u $QUAY_USERNAME -p QUAY_PASSWORD
    - run:
        name: docker build
        command: docker build -t quay.io/giantswarm/reporting-agent:$CIRCLE_SHA .

    - deploy:
        command: |
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            docker push quay.io/giantswarm/reporting-agent:$CIRCLE_SHA
          fi
