version: 2
jobs:
  build:
    machine: true
    steps:
    - checkout

    - run:
        name: install helm
        command: .circleci/install.sh
    - run:
        name: set env tag
        command: echo 'export TAG=$(cat helm/reporting-agent-chart/Chart.yaml | grep version | awk \'{ print $2 }\')' >> $BASH_ENV
    - run:
        name: display env tag
        command: echo ${TAG} $TAG
    - run:
        name: helm lint
        command: helm lint ./helm/reporting-agent-chart
    - run:
        name: docker login
        command: docker login quay.io -u $QUAY_USERNAME -p $QUAY_PASSWORD
    - run:
        name: docker build
        command: docker build -t quay.io/giantswarm/reporting-agent:${TAG} .

    - deploy:
        command: |
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            docker push quay.io/giantswarm/reporting-agent:${TAG}
          fi
